---
- name: "Make sure loudness_exporter.service is restarted"
  listen: 'systemctl restart loudness_exporter.service'
  become: true
  ansible.builtin.systemd_service:
    name: 'loudness_exporter.service'
    state: restarted
    enabled: true
  when: ansible_service_mgr == "systemd"
