---
- name: Run simple versionscheck (optional)
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Create User for loudness exporter
  ansible.builtin.include_tasks:
    file: 'user.yml'

- name: Install Packages for lufs exporter
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Create loudness python venv
  ansible.builtin.include_tasks:
    file: 'python_venv.yml'

- name: Create Loudness script
  become: true
  ansible.builtin.template:
    src: 'templates/loudness_exporter.py.j2'
    owner: "{{ lufs_exporter__user }}"
    group: "{{ lufs_exporter__group }}"
    dest: "{{ lufs_exporter__home }}/loudness_exporter.py"
