---
- name: Update apt repo-cache on debian/ubuntu hosts
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_pkg_mgr == "apt"

- name: Install Required packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  loop:
    - 'python3-dev'
    - 'python3-venv'
    - 'python3'
    - 'python3-pip'
    - 'python3-virtualenv'
  notify: 'systemctl restart loudness_exporter.service'
